### ISSUE TITLE
Challenges Slides for Final Presentation

### ISSUE THREAD

**Issue by tmyarow** [tmyarow/CS3704_Project#3]
Create slide(s) outlining major problems we faced as we designed the application and what the solutions are that we came up with

**Comment by amrios** [comment]
I created some issues. I'll probably discuss more when we meet in-person, however here is the summary of what I found.

Which of our use-cases are logically cohesive?
We started off by grouping what these use-cases correlated in general with the operating duties of a restaurant. Later on, we reviewed these duties and started examining whether they had a correlation with a common group. All together, the end result was presented in the pic on the side.

Deciding on UI/UX guidelines
UI/UX was the hardest in terms of dividing group. If we were to divide certain portions of our design to different people, it would be very jarring to use the app. Our solution was to try to make one person come up with some sort of UI and copy it. This made UI much more uniform compared to if we were to make every person do their portion without having any guidance.
I might possibly add that UI can be further improved upon further revisions when we meet in-person.

Who should handle credit card processing?
A lot of smaller companies often outsource payment processing to other companies since compliance in this space is hard without having someone knowledgeable in this space. If we try to do processing, then it might inconvenience some customers who want to do it in-house. However, we determined that customers for this app are likely to be small, therefore would like help in processing payment with credit/debit.
